version: '3'

services:
  pihole:
    image: 'pihole/pihole:latest'
    container_name: pihole
    volumes:
      - ~/pihole/:/etc/pihole/ 
    dns: 
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - "NET_ADMIN"
    restart: "unless-stopped"
    ports:
      - 80:80
      - 53:53/tcp
      - 53:53/udp
      - 443:443
    environment:
      - ServerIP=${SERVER_IP}
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - DNS1=${DNS1}
      - DNS2=${DNS2}