version: '3.0'

services:
  pihole:
    build:
      context: ./
    container_name: pihole
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    image: pyhole_ngz
    env_file:
      - ./.env
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - "NET_ADMIN"
    restart: "unless-stopped"
    ports:
      - ${PIHOLE_WEBPORT:-80}:80/tcp
      - 53:53/udp
      - 53:53/tcp
      - 443:443/tcp
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=${TZ:-UTC}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=${PIHOLE_DNS_}
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single
      - WEBTHEME=${WEBTHEME:-default-light}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound: