version: '3.0'

services:
  pihole:
    build:
      context: ./
    container_name: pihole
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    image: pyhole_ngz
    env_file:
      - ./.env
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - "NET_ADMIN"
    restart: "unless-stopped"
    ports:
      - 80:80
      - 53:53/tcp
      - 53:53/udp
      - 443:443
    environment:
      - FTLCONF_REPLY_ADDR4=${FTLCONF_REPLY_ADDR4}
      - TZ=${TZ}
      - WEBPASSWORD=${WEBPASSWORD}
      - PIHOLE_DNS_=${PIHOLE_DNS_}
      - DNSSEC="true"
      - DNSMASQ_LISTENING=single

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:
